analyze_keyword_rankings_data:
  description: >
    As a Senior SEO Data Analyst, analyze the keyword performance data from both competitor and user rankings:
    1. First analyze competitor rankings data:
       - Use the FileReadTool to read competitor_rankings.json
       - For each competitor domain, examine:
         - ALL keyword rankings and positions
         - ALL search volumes
         - ALL keyword difficulty scores
         - ALL top ranking URLs (hyperlink each url on word 'Link')
       - Create detailed tables showing ALL competitor keyword metrics
       - Identify patterns and insights across ALL competitor domains
    2. Then analyze user rankings data:
       - Use the FileReadTool to read user_rankings.json
       - Create tables showing:
         - Keyword rankings and positions
         - Search volumes
         - Keyword difficulty scores
         - Top ranking URLs
       - Compare performance against ALL competitor benchmarks
       - Identify ALL gaps and opportunities
    3. Provide strategic recommendations:
       - Compare user vs ALL competitor keyword targeting
       - Highlight areas where user rankings lag behind ALL competitors
       - Suggest specific keywords to focus on improving
       - Recommend content and optimization strategies
       - Set realistic ranking improvement targets
    Present all findings based strictly on the real data from both ranking files, without making any assumptions
    or using external information.
    Never mention the source of your data in any case.
  expected_output: >
    Generate an SEO Keyword Performance Analysis report.
    Include the following sections:\n
    1. Competitor Keyword Analysis: Create a table for each competitor (all the 5 competitors) showing
    all 10 keywords for each competitor, Top Ranked URL, Rank, Search Volume, and Keyword Difficulty.
    Add Patterns and Insights below the table.\n
    2. User Keyword Analysis: Create a table for user keywords showing all 10 keywords, Top Ranked URL, Rank,
    Search Volume, and Keyword Difficulty.\n
    3. Comparative Analysis: Highlight key differences between competitor and user keyword performance.\n
    4. Strategic Recommendations: Provide actionable suggestions for improving keyword rankings.


generate_ad_copies:
  description: >
    Create high-performing ad copies for both Google Ads and Meta Ads platforms that improves student
    perception and enrollments of Jaipuria Institute of Management when compared to other top b-schools in India.
    Note that Jaipuria Institute of Management does not provide any entranace exam preparation for CAT/CET/XAT etc.,
    neither does it offer Group discussion or Personal interview preparation for MBA selection processes.
    However you can provide insights for these from a neutral standpoint to increase informative value and brand
    awareness of Jaipuria and create positive perceptions in the mind of the potential student seeking admission
    in Jaipuria Institute of Management.
    IMPORTANT PREPARATION STEPS:
    1. First, thoroughly review ALL the provided website url of Jaipuria Institute of Management
       - Extract key unique selling points
       - Understand the institute's history, mission, and different MBA programs offered
       - Understand 'Why Jaipuria', 'Admissions', 'Placement', 'Faculty', 'Campus', 'Alumni', 'Rankings', 'Awards', 'Events', 'News', 'Contact Us'
       - Extract Awards and Recognition
       - Get the Placement story of Jaipuria Institute of Management
    2. Then, analyze the keyword data from selected_keywords_details.json to identify:
       - High commercial intent keywords
       - Keywords with good search volume
       - Keywords relevant to student recruitment, admissions, placement, faculty, campus, alumni, rankings
    3. Use SerperDevTool to:
       - Research competitor ad strategies
       - Analyze competitor landing pages
       - Understand search intent
    4. Create ad copies that:
       - Incorporate authentic details from the Jaipuria Institute of Management knowledge sources
       - Highlight the institute's unique value propositions
       - Use factual information to build credibility
       - Focus on attracting potential students and their parents
    5. For Google Ads, ALWAYS create and give 5 ad variations that:
       - Follow the Responsive Search Ads format
       - Include 3 headlines (30 chars max each)
       - Have 2 descriptions (90 chars max each)
       - Incorporate target keywords naturally
       - Include clear calls-to-action
       - Focus on unique value propositions
       - Highlight key programs and accreditations
    6. For Meta Ads, ALWAYS create and give 5 ad variations that:
       - Follow Meta Ads format requirements
       - Include primary text (125 chars max)
       - Have compelling headlines (40 chars max)
       - Include descriptions (30 chars max)
       - Focus on visual-friendly messaging
       - Create emotional connection
       - Drive social engagement
    7. For each ad copy:
       - Include character count for each element
       - Mark recommended combinations
       - Add notes on targeting suggestions
  expected_output: >
    A markdown document with two main sections:
    1. Google Ads Copies:
       - 5 complete ad variations with all components
       - Character counts for each element
       - Recommended headline-description combinations
       - Target keyword suggestions
       - A/B testing notes
    2. Meta Ads Copies:
       - 5 complete ad variations with all components
       - Character counts for each element
       - Recommended visuals/creatives notes
       - Audience targeting suggestions
       - A/B testing recommendations
    Format each ad copy in a clear, structured way with proper markdown formatting.
    Include a summary of best practices and optimization tips for each platform.


generate_blog_post_outlines:
  description: >
    1. First use the FileReadTool to read 2_ad_copies.md file to get the ad copies for Google Ads and Meta Ads
    2. Then use the FileReadTool to read selected_keywords_details.json to get the details of the selected keywords
    3. Next, ONLY from selected_keywords_details.json, choose 5 keywords that are included in the file and
    have the potential to surpass the content on the topRankedUrl, in order to create blog outlines for Jaipuria Institute of Management:
       - Generate a detailed blog outline designed to outperform the content on the topRankedUrl.
       - Ensure the blog outline content is factual, balanced, and avoids controversial topics.
       - Focus exclusively on Jaipuria Institute of Management's offerings and expertise.
       - Incorporate insights from the analysis to enhance the outline's relevance and depth.
    For ad copies and keyword data, use ONLY the data from the 2_ad_copies.md and selected_keywords_details.json files.
  expected_output: >
    A markdown document with ALL the 5 (1-5) blog post outlines tailored ONLY for 'Jaipuria Institute of Management'.
    DON'T promote, compare with, or mention any other institution's name.
    Each outline must start with:
    # Blog Outline
    ## Content outline:
    - Blog title incorporating the exact keyword
    - Meta description
    - Sections with proper formatting and detailed sub-headings designed to outperform the ranking URL
    - Word count (recommend for at least 1000-1500 words) and formatting recommendations
    - Content must be factual, non-controversial and focused on Jaipuria's expertise
    Add "---" after each blog outline to separate them.
    Do not write any thing other than the blog outlines.
